Repository The-SourceCode/Open-SourceBot, pull requests merged in 2019-03, with the labels that each got.

#18 Guide now contains step for making changes and checking tests
  .github/CONTRIBUTING.md
Labels: Meta: Documentation

#22 Set ESLint require-await rule
  .eslintrc.json
Labels: Meta: ESLint

#23 Slight correction in README
  README.md
Labels: Meta: Documentation

#24 Make Command class options optional
  src/handler/Command.js
Labels: Meta: Framework

#21 Added the logic for Handler#load
  src/Utils.js
  src/handler/Command.js
  src/handler/Handler.js
Labels: Meta: Framework

#25 Added aliases type check
  src/handler/Command.js
Labels: Meta: Framework

#19 Better Looking Readme
  README.md
Labels: Meta: Documentation

#27 Handler now checks against prototype instead of object instance
  src/handler/Event.js
  src/handler/Handler.js
Labels: Meta: Framework

#16 Adding Toggle abilities to Commands.
  src/handler/Command.js
  src/handler/Event.js
  src/handler/Toggleable.js
Labels: Meta: Framework
