Repository The-SourceCode/Open-SourceBot, pull requests merged in 2019-07, with the labels that each got.

#32 Message/Event handler implementation
  src/handler/Command.js
  src/handler/Handler.js
  src/index.js
  src/modules/economy/commands/coins.js
  src/modules/economy/economy.js
  src/modules/economy/events/chat.js
  src/modules/general/commands/help.js
  src/modules/general/commands/ping.js
  src/modules/general/events/start.js
Labels: Meta: Framework

#36 Fixed issue with aliases not working
  src/handler/Handler.js
Labels: Meta: Framework

#37 Add prettier for a stricter code style
  .eslintrc.js
  .prettierrc.js
  package.json
  src/Utils.js
  src/handler/Command.js
  src/handler/Feature.js
  src/handler/Handler.js
  src/index.js
  src/modules/general/commands/ping.js
Labels: Meta: ESLint

#38 Update issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: Meta: Documentation
